// Support-ticket plumbing — bridge between the public /support form
// on the quiz site and the private "Support Tickets" category on the
// Discourse forum.
//
// Flow:
//   1. User submits the form → server action validates, calls
//      createSupportTicket() which posts a topic to Discourse via
//      the bot user's API key.
//   2. Admins reply in Discourse with `@support_bot respond [msg]`.
//      The plugin POSTs back to /api/support/respond, which uses the
//      quiz site's existing email-provider abstraction to email the
//      submitter.
//
// Env required (set in Vercel):
//   DISCOURSE_BASE_URL       — https://discuss.miaswebsites.art
//   DISCOURSE_BOT_API_KEY    — generated by seed-support-system.rb
//   DISCOURSE_BOT_USERNAME   — defaults to "support_bot"
//   DISCOURSE_SSO_SECRET     — used to verify the respond callback's
//                              HMAC signature (already configured)

import { db, schema } from "@/db";
import { and, desc, eq } from "drizzle-orm";
import { id as makeId } from "@/lib/ids";

const DEFAULT_BASE = "https://discuss.miaswebsites.art";
const DEFAULT_BOT_USERNAME = "support_bot";
const SUPPORT_CATEGORY_SLUG = "support-tickets";

export type CreateTicketInput = {
  // Submitter contact info — captured from the form; both required.
  name: string;
  email: string;
  // Short title (one sentence). Becomes the topic title.
  subject: string;
  // Free-form body. Markdown allowed.
  message: string;
  // Optional category tag (e.g. "bug", "tournament", "billing").
  // Stored as a Discourse tag for filtering.
  topic?: string;
  // If the submitter is signed in, link the ticket to them by user
  // id. Helps admins see context (their tournament status, etc.).
  // Anonymous submissions leave this null.
  submitterUserId?: string | null;
};

export type CreateTicketResult =
  | { ok: true; topicId: number; postId: number; url: string }
  | { ok: false; error: string };

function discourseBase(): string {
  return process.env.DISCOURSE_BASE_URL ?? DEFAULT_BASE;
}
function botApiKey(): string | null {
  return process.env.DISCOURSE_BOT_API_KEY ?? null;
}
function botUsername(): string {
  return process.env.DISCOURSE_BOT_USERNAME ?? DEFAULT_BOT_USERNAME;
}

// Resolve the support-tickets category id once per Lambda lifetime.
let cachedCategoryId: number | null = null;
async function resolveSupportCategoryId(): Promise<number | null> {
  if (cachedCategoryId !== null) return cachedCategoryId;
  const key = botApiKey();
  if (!key) return null;
  try {
    // `/c/<slug>.json` 301-redirects to `/c/<slug>/<id>.json`, which
    // returns the topic list (no `category` metadata field). We want
    // metadata, so use `/c/<slug>/show.json` directly.
    const res = await fetch(
      `${discourseBase()}/c/${SUPPORT_CATEGORY_SLUG}/show.json`,
      {
        headers: {
          "Api-Key": key,
          "Api-Username": botUsername(),
          accept: "application/json",
        },
        cache: "no-store",
      }
    );
    if (!res.ok) return null;
    const json = (await res.json()) as { category?: { id: number } };
    const id = json?.category?.id ?? null;
    if (id) cachedCategoryId = id;
    return id;
  } catch {
    return null;
  }
}

export async function createSupportTicket(
  input: CreateTicketInput
): Promise<CreateTicketResult> {
  const key = botApiKey();
  if (!key) {
    return {
      ok: false,
      error:
        "Support system not configured (DISCOURSE_BOT_API_KEY missing). Tell Sam.",
    };
  }
  const categoryId = await resolveSupportCategoryId();
  if (!categoryId) {
    return { ok: false, error: "Could not find Support Tickets category." };
  }

  // Format the topic body so admins see all the metadata at the top.
  // The submitter's email is the load-bearing field (used by the
  // bot's `respond` command); we also stash it on topic
  // custom_fields, but having it in the post body helps debugging.
  const submitterLine = input.submitterUserId
    ? `**From:** ${input.name} <${input.email}> · _signed-in user id_ \`${input.submitterUserId}\``
    : `**From:** ${input.name} <${input.email}> · _anonymous_`;

  const raw = [
    submitterLine,
    `**Submitted:** ${new Date().toISOString()}`,
    input.topic ? `**Topic:** ${input.topic}` : null,
    "",
    "---",
    "",
    input.message,
    "",
    "---",
    "",
    "_Reply with `@support_bot respond [message]` to email the submitter, or `@support_bot internalnote [staff note]`, or `@support_bot changestatus [open|pending|resolved|closed]`._",
  ]
    .filter((s) => s !== null)
    .join("\n");

  // Stable title — prefix with [Ticket] so the category list reads
  // cleanly. Truncate to 200 chars (Discourse default max).
  const safeSubject = input.subject.slice(0, 180).replace(/\s+/g, " ").trim();
  const title = `[Ticket] ${safeSubject || "(no subject)"}`;

  const tags = ["support-ticket"];
  if (input.topic) tags.push(`topic-${slugifyTag(input.topic)}`);

  try {
    const res = await fetch(`${discourseBase()}/posts.json`, {
      method: "POST",
      headers: {
        "Api-Key": key,
        "Api-Username": botUsername(),
        "Content-Type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify({
        title,
        raw,
        category: categoryId,
        tags,
        archetype: "regular",
      }),
    });
    if (!res.ok) {
      const text = await res.text();
      return {
        ok: false,
        error: `Discourse ${res.status}: ${text.slice(0, 200)}`,
      };
    }
    const json = (await res.json()) as {
      id: number;
      topic_id: number;
      topic_slug: string;
    };

    // Stamp the ticket-specific custom fields so the plugin's bot
    // commands can find email/name later, and so the topic shows up
    // in any "open tickets" filter.
    void stampTicketFields(json.topic_id, {
      email: input.email,
      name: input.name,
      status: "open",
    });

    // Persist locally so the portal can list a user's tickets
    // without searching Discourse. Best-effort — failures here
    // shouldn't block the submission flow (the topic in Discourse
    // is the source of truth).
    try {
      await db
        .insert(schema.supportTickets)
        .values({
          id: makeId(),
          discourseTopicId: json.topic_id,
          discoursePostId: json.id,
          subject: input.subject,
          submitterEmail: input.email,
          submitterName: input.name,
          submitterUserId: input.submitterUserId ?? null,
          topic: input.topic ?? null,
          status: "open",
        })
        .onConflictDoNothing();
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error("local ticket insert failed:", err);
    }

    return {
      ok: true,
      topicId: json.topic_id,
      postId: json.id,
      url: `${discourseBase()}/t/${json.topic_slug}/${json.topic_id}`,
    };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "fetch failed",
    };
  }
}

// ─── portal helpers ────────────────────────────────────────────────────

export type LocalTicket = typeof schema.supportTickets.$inferSelect;

// Return all tickets a logged-in user has submitted, newest first.
export async function listTicketsForUser(userId: string): Promise<LocalTicket[]> {
  return db
    .select()
    .from(schema.supportTickets)
    .where(eq(schema.supportTickets.submitterUserId, userId))
    .orderBy(desc(schema.supportTickets.createdAt));
}

// Same, but by email — covers anonymous submissions where the user
// signs up later. Useful for a "track by email" feature.
export async function listTicketsForEmail(email: string): Promise<LocalTicket[]> {
  return db
    .select()
    .from(schema.supportTickets)
    .where(eq(schema.supportTickets.submitterEmail, email.toLowerCase()))
    .orderBy(desc(schema.supportTickets.createdAt));
}

export async function getTicketByTopicId(
  topicId: number
): Promise<LocalTicket | null> {
  const [row] = await db
    .select()
    .from(schema.supportTickets)
    .where(eq(schema.supportTickets.discourseTopicId, topicId))
    .limit(1);
  return row ?? null;
}

// Pull the message thread for a ticket from Discourse. Returns
// posts in order, with whisper (internal-note) posts filtered out
// since the portal is the submitter's view.
export type TicketMessage = {
  postId: number;
  authorUsername: string;
  authorName: string | null;
  authorIsBot: boolean;
  authorIsAdmin: boolean;
  postedAt: Date;
  rawHtml: string;
  rawMarkdown: string;
};

export async function fetchTicketThread(
  topicId: number
): Promise<TicketMessage[]> {
  const key = botApiKey();
  if (!key) return [];
  try {
    const res = await fetch(
      `${discourseBase()}/t/${topicId}.json?include_raw=true`,
      {
        headers: {
          "Api-Key": key,
          "Api-Username": botUsername(),
          accept: "application/json",
        },
        cache: "no-store",
      }
    );
    if (!res.ok) return [];
    const json = (await res.json()) as {
      post_stream?: {
        posts?: Array<{
          id: number;
          username: string;
          name: string | null;
          post_type: number;
          created_at: string;
          cooked: string;
          raw?: string;
          admin?: boolean;
        }>;
      };
    };
    const posts = json?.post_stream?.posts ?? [];
    const bot = botUsername();
    const filtered = posts
      // Filter whispers (post_type 4) — those are internal admin notes.
      .filter((p) => p.post_type !== 4)
      // Filter admin command posts: raw starts with @support_bot. The
      // bot's reply (in a separate post) is the user-facing message.
      .filter((p) => {
        const raw = (p.raw ?? "").trimStart();
        return !new RegExp(`^@${bot}\\b`, "i").test(raw);
      })
      // Filter bot meta acknowledgments (help text, usage hints,
      // unknown-command replies, "only works inside" warnings).
      .filter((p) => {
        if (p.username !== bot) return true;
        const r = p.raw ?? "";
        if (/^\s*\*\*Support bot commands\*\*/im.test(r)) return false;
        if (/^\s*🤔\s+(Usage|Unknown command|Status must be one)/im.test(r))
          return false;
        if (/only works inside the \*\*Support Tickets\*\*/i.test(r))
          return false;
        return true;
      });

    return filtered.map<TicketMessage>((p, i) => ({
      postId: p.id,
      authorUsername: p.username,
      authorName: p.name,
      authorIsBot: p.username === bot,
      authorIsAdmin: !!p.admin,
      postedAt: new Date(p.created_at),
      // For the FIRST post (the original ticket), strip the admin
      // metadata header + the trailing "_Reply with @support_bot…_"
      // instructions so the submitter sees only their message.
      rawHtml:
        i === 0 ? cleanFirstPostHtml(p.cooked ?? "") : p.cooked ?? "",
      rawMarkdown:
        i === 0 ? cleanFirstPostRaw(p.raw ?? "") : p.raw ?? "",
    }));
  } catch {
    return [];
  }
}

// Add a reply to a ticket as the submitter. Posts to Discourse via
// the bot API, attributed to the bot but with a header indicating
// the original submitter (so admins know who replied).
export async function replyToTicketAsSubmitter(args: {
  topicId: number;
  submitterName: string;
  submitterEmail: string;
  message: string;
}): Promise<{ ok: true; postId: number } | { ok: false; error: string }> {
  const key = botApiKey();
  if (!key) return { ok: false, error: "bot key not configured" };
  const raw = [
    `**📩 Reply from ${args.submitterName}** _<${args.submitterEmail}>_`,
    "",
    args.message,
  ].join("\n");
  try {
    const res = await fetch(`${discourseBase()}/posts.json`, {
      method: "POST",
      headers: {
        "Api-Key": key,
        "Api-Username": botUsername(),
        "Content-Type": "application/json",
        accept: "application/json",
      },
      body: JSON.stringify({ topic_id: args.topicId, raw }),
    });
    if (!res.ok) {
      const text = await res.text();
      return {
        ok: false,
        error: `Discourse ${res.status}: ${text.slice(0, 200)}`,
      };
    }
    const json = (await res.json()) as { id: number };
    // Bump local ticket status back to open if it was waiting.
    try {
      await db
        .update(schema.supportTickets)
        .set({ status: "open", updatedAt: new Date() })
        .where(
          and(
            eq(schema.supportTickets.discourseTopicId, args.topicId),
            eq(schema.supportTickets.status, "pending")
          )
        );
    } catch {
      // non-fatal
    }
    return { ok: true, postId: json.id };
  } catch (e) {
    return {
      ok: false,
      error: e instanceof Error ? e.message : "fetch failed",
    };
  }
}

// Helper: build the absolute URL of a ticket's Discourse topic.
export function ticketUrl(topicId: number): string {
  return `${discourseBase()}/t/${topicId}`;
}

// Strip the admin-facing header + trailing instructions from the
// first post in a ticket thread, leaving just the submitter's
// original message body.
//
// Format the ticket-creation post follows:
//   **From:** ... \n **Submitted:** ... \n [maybe Topic line]
//   ---
//   <user's actual message>
//   ---
//   _Reply with `@support_bot ...`_
function cleanFirstPostRaw(raw: string): string {
  // Try to extract the section between the first two `---` separators.
  // Falls back to stripping known prefix/suffix lines if separators
  // aren't present.
  const parts = raw.split(/^\s*---\s*$/m);
  if (parts.length >= 3) {
    return parts[1].trim();
  }
  // Fallback: drop lines starting with "**From:**", "**Submitted:**",
  // "**Topic:**" and the trailing "_Reply with @support_bot…_" line.
  return raw
    .split("\n")
    .filter(
      (line) =>
        !/^\*\*(From|Submitted|Topic):\*\*/i.test(line.trim()) &&
        !/_Reply with `@support_bot/i.test(line)
    )
    .join("\n")
    .trim();
}

// Same idea but for already-cooked HTML. Discourse renders the
// markdown `---` as `<hr>`, so we split on that.
function cleanFirstPostHtml(cooked: string): string {
  const parts = cooked.split(/<hr\s*\/?>/i);
  if (parts.length >= 3) {
    return parts[1].trim();
  }
  // Defensive fallback: strip any <p> containing the From/Submitted/
  // Reply-with-@support_bot text.
  return cooked.replace(
    /<p[^>]*>(?:\s*<strong>(?:From|Submitted|Topic):<\/strong>[^<]*<\/p>|\s*<em>Reply with[\s\S]*?<\/em>\s*<\/p>)/gi,
    ""
  );
}

// Best-effort: tag the topic's custom fields via Discourse's
// `topics/<id>.json` PUT. Custom fields aren't directly settable via
// the API, but we use the topic update endpoint which accepts custom
// fields when the API user is admin/staff (the bot is in authors,
// which is enough for category-mod abilities).
async function stampTicketFields(
  topicId: number,
  fields: { email: string; name: string; status: string }
): Promise<void> {
  const key = botApiKey();
  if (!key) return;
  try {
    await fetch(`${discourseBase()}/t/-/${topicId}.json`, {
      method: "PUT",
      headers: {
        "Api-Key": key,
        "Api-Username": botUsername(),
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        topic: {
          custom_fields: {
            qb_is_support_ticket: "true",
            qb_ticket_status: fields.status,
            qb_ticket_email: fields.email,
            qb_ticket_name: fields.name,
          },
        },
      }),
    });
  } catch {
    // Swallow — admins can manually set status/email if needed.
  }
}

function slugifyTag(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 30);
}
