// Text-to-speech endpoint backed by Groq Orpheus, with R2 caching.
//
// Three layers of caching, cheapest first:
//   1) Vercel edge CDN — same URL → same response, no function run.
//   2) Cloudflare R2 — durable cache by SHA-1 of the text. First user
//      to ask for a particular question pays the Groq generation;
//      every subsequent user pulls bytes from R2 (no Groq cost).
//   3) Groq Orpheus — only on R2 miss.
//
// Auth + hash gate are still enforced before we touch R2 so a
// drive-by attacker can't pump arbitrary text and have us upload it.
//
// Caller pattern: client SHA-1's the text in the browser, then opens
//   /api/tts?h=<hash>&t=<encoded text>
// Helper in components/TTSButton.tsx wraps that.

import { NextRequest, NextResponse } from "next/server";
import { createHash } from "node:crypto";
import { currentUser } from "@/lib/session";
import { generateSpeech } from "@/lib/groq";
import {
  getObjectBytes,
  putObjectBytes,
  isR2Configured,
} from "@/lib/r2";

export const runtime = "nodejs";
// Don't pre-render — we always need to evaluate the request.
export const dynamic = "force-dynamic";

// Per-user rate limit on Groq cost. Cache hits don't reach this code
// (CDN serves them straight back), so this only counts UNIQUE-text
// requests per user. 30 unique generations per hour is way more than
// any honest player needs and bounds the worst-case Groq spend if a
// signed-in user goes rogue.
const RATE_WINDOW_MS = 60 * 60 * 1000;
const RATE_MAX = 30;
const rateBuckets = new Map<string, number[]>();

function rateLimit(userId: string): boolean {
  const now = Date.now();
  const cutoff = now - RATE_WINDOW_MS;
  const bucket = (rateBuckets.get(userId) ?? []).filter((t) => t > cutoff);
  if (bucket.length >= RATE_MAX) {
    rateBuckets.set(userId, bucket);
    return false;
  }
  bucket.push(now);
  rateBuckets.set(userId, bucket);
  return true;
}

export async function GET(req: NextRequest) {
  const user = await currentUser();
  if (!user) {
    return NextResponse.json({ error: "auth required" }, { status: 401 });
  }

  const url = new URL(req.url);
  const text = url.searchParams.get("t");
  const hash = url.searchParams.get("h");

  if (!text || !hash) {
    return NextResponse.json({ error: "missing t or h" }, { status: 400 });
  }
  if (text.length > 800) {
    return NextResponse.json({ error: "text too long" }, { status: 400 });
  }

  const expected = createHash("sha1").update(text).digest("hex");
  if (expected !== hash) {
    // Client-supplied hash doesn't match — reject. This forces clients to
    // know the exact text to trigger a generation, so a lazy attacker can't
    // pump endless garbage strings to bill Groq.
    return NextResponse.json({ error: "bad hash" }, { status: 400 });
  }

  // R2 cache hit — serve durable bytes without burning a Groq call.
  // R2 is the source of truth for cached audio; it survives Vercel CDN
  // evictions and cold starts.
  const r2Key = `tts/${hash}.wav`;
  let audio: Uint8Array | null = null;
  let cacheStatus: "hit" | "miss" | "skipped" = "skipped";

  if (isR2Configured()) {
    try {
      const cached = await getObjectBytes(r2Key);
      if (cached?.bytes && cached.bytes.length > 0) {
        audio = cached.bytes;
        cacheStatus = "hit";
      } else {
        cacheStatus = "miss";
      }
    } catch (e) {
      // R2 read failed — fall through to generation. We don't fail the
      // request just because the cache is unreachable.
      // eslint-disable-next-line no-console
      console.error("R2 read failed:", e);
      cacheStatus = "miss";
    }
  }

  if (!audio) {
    // Only count rate limit on cache misses — we're about to actually
    // bill Groq here. Cache hits don't count.
    if (!rateLimit(user.id)) {
      return NextResponse.json(
        { error: "rate limit — too many TTS generations this hour" },
        { status: 429 }
      );
    }
    try {
      audio = await generateSpeech(text);
    } catch (e) {
      const msg = e instanceof Error ? e.message : "unknown";
      return NextResponse.json({ error: msg }, { status: 502 });
    }
    // Persist to R2 so subsequent users (and our own future requests)
    // skip Groq. Best-effort: if the upload fails, we still serve the
    // generated bytes back to this user — next request will retry.
    if (isR2Configured()) {
      try {
        await putObjectBytes({
          key: r2Key,
          bytes: audio,
          contentType: "audio/wav",
          cacheControl: "public, max-age=31536000, immutable",
        });
      } catch (e) {
        // eslint-disable-next-line no-console
        console.error("R2 write failed (audio still served):", e);
      }
    }
  }

  // Convert to a Buffer-backed body so the Response is happy.
  return new NextResponse(audio as unknown as BodyInit, {
    status: 200,
    headers: {
      // Orpheus returns WAV bytes. Modern browsers play WAV via
      // <audio> without trouble; size is larger than mp3 but R2 +
      // CDN make that a one-time cost per question.
      "content-type": "audio/wav",
      // Browser cache + Vercel CDN cache. The URL is uniquely keyed by
      // (text, hash) so repeated plays of the same prompt skip Groq.
      "cache-control": "public, max-age=31536000, immutable",
      "cdn-cache-control": "public, max-age=31536000, immutable",
      "vercel-cdn-cache-control": "public, max-age=31536000, immutable",
      // Diagnostic — visible in browser devtools / vercel logs to
      // confirm caching is working.
      "x-tts-cache": cacheStatus,
    },
  });
}
